// <auto-generated />
using System;
using AchatEnLigne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchatEnLigne.Migrations
{
    [DbContext(typeof(AchatEnLigneContext))]
    [Migration("20230114100908_kslflg")]
    partial class kslflg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AchatEnLigne.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NombreArticles")
                        .HasColumnType("int");

                    b.Property<int>("NumCommande")
                        .HasColumnType("int");

                    b.Property<int?>("PanierId")
                        .HasColumnType("int");

                    b.Property<int>("User")
                        .HasColumnType("int");

                    b.Property<int>("produit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PanierId");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("AchatEnLigne.Models.LignePanierCommande", b =>
                {
                    b.Property<int>("LignepanierCommandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LignepanierCommandeId"), 1L, 1);

                    b.Property<int?>("CommandeId")
                        .HasColumnType("int");

                    b.Property<float>("CommandeX")
                        .HasColumnType("real");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("UserX")
                        .HasColumnType("real");

                    b.HasKey("LignepanierCommandeId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("UserId");

                    b.ToTable("LignePanierCommande");
                });

            modelBuilder.Entity("AchatEnLigne.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NombreArticles")
                        .HasColumnType("int");

                    b.Property<int>("Produit")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<int>("User")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("AchatEnLigne.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("AchatEnLigne.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AchatEnLigne.Models.Commande", b =>
                {
                    b.HasOne("AchatEnLigne.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("PanierId");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("AchatEnLigne.Models.LignePanierCommande", b =>
                {
                    b.HasOne("AchatEnLigne.Models.Commande", "Commande")
                        .WithMany("LignePanierCommande")
                        .HasForeignKey("CommandeId");

                    b.HasOne("AchatEnLigne.Models.User", "User")
                        .WithMany("LignePanierCommande")
                        .HasForeignKey("UserId");

                    b.Navigation("Commande");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AchatEnLigne.Models.Commande", b =>
                {
                    b.Navigation("LignePanierCommande");
                });

            modelBuilder.Entity("AchatEnLigne.Models.User", b =>
                {
                    b.Navigation("LignePanierCommande");
                });
#pragma warning restore 612, 618
        }
    }
}
